### ISSUE TITLE
Detail roadmap for changing to SWDM v4 as default

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/co2.js#209]
The purpose of this issue is to track the process of transitioning to using the Sustainable Web Design Model (SWDM) version 4 as the default model in CO2.js.

Currently, SWDM is the default model used by the library. Developers have the option to switch models ([see docs](https://developers.thegreenwebfoundation.org/co2js/models/)) between SWDM and OneByte. With the implementation of SWDM v4 developers also have the option to now switch between different version of SWMD (see #208). **The default SWDM version used by CO2.js is version 3, and developers have to opt-in to switching to the newer version 4 methodology.**

In the same way as we previously switched the default model from OneByte to SWDM (see #100) we would also want to eventually update the library to use SWDM version 4 as the default methodology. 

While it is not expected that this would be a breaking change, we would still approach this very gradually and communicate it with developers well ahead of time. This issue tracks those tasks, as well as provides a place for conversation about the switch to the newer methodology.

Tasks:

- [x] **[DECISION]** _Decide on a date/version in which SWDM version 4 will be set as the default_
- [x] **[DECISION]** _Will SWDM version 3 be _removed_ from CO2.js or simply left for developers to "opt-in" to using?_
- [x] Add warning to CO2.js when developers use SWDM version 3
- [x] Update documentation site to reflect this information
- [x] Update the CO2.js page on the Green Web Foundation site to reflect this information
- [x] Update the CO2.js quick start guide to reflect this information
- [ ] Publish announcements through regular release communication channels (LinkedIn, Slack)
- [ ] Prepare Pull Request for change
- [ ] Merge change
- [ ] Publish regular release communication to notify of change

**Additional context (if applicable)**
Related to PR: #208 
Related to Issue: #119

**Comment by fershad** [comment]
Released. https://www.thegreenwebfoundation.org/news/release-guide-co2-js-v0-18/
