### ISSUE TITLE
Switch default to use SWD model instead of older onebyte model

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/co2.js#94]
Right now, while we have the Sustainable Web Design module, we default using to the earlier created 1byte model for CO2 calculations.

So when you do this:

```js
import { CO2 } from '@tgwf/co2'

const calc = new CO2()

// calculate transfer
const basicTransferResult = calc.perbyte(TRANSFER_IN_BYTES)

```

...you're using the 1byte model from the Shift Project.

#### Making the change.

We need to change this code so default model is no longer the `Onebyte` one, and instead the SWD one:

```js
class CO2 {
  constructor(options) {
    this.options = options;

    // default model
    this.model = new OneByte();

    if (options) {
      this.model = new options.model();
    }
  }
```

This would mean when we import the CO2 module, we can calculate web pages easily, not just do basis transfer calculations.

```js
import { CO2 } from '@tgwf/co2'

const calc = new CO2()

// calculate transfer
const basicTransferResult = calc.perbyte(TRANSFER_IN_BYTES)

// new: calculate the result for a web page, including caching assumptions in the SWD model
const webPageResult = calc.energyPerVisit(WEBSITE_SIZE_IN_BYTES)
```

This will have the effect of increasing carbon numbers slightly but it also means we can get a breakdown of where the emissions are assumed to happen.

### Todo

- [ ] Switch default model to SWD one
- [ ] Update tests to reflect increased numbers
- [ ] Update docs and code examples to refer to SWD model by default
- [ ] Update changelog to mention change of model

**Comment by fershad** [comment]
@mrchrisadams I'll assign this to myself and work on it this coming week.

**Comment by fershad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CO2.js - Switch default to use SWD model instead of 1byte model](https://trello.com/c/lnwwngVg/35-co2js-switch-default-to-use-swd-model-instead-of-1byte-model)

**Comment by fershad** [comment]
#100 has been created to address this issue.

**Comment by fershad** [comment]
This issue was merged with #100.
